//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectViolent
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorizationData
    {
        public string Login { get; set; }
        public int UserID { get; set; }
        public string SecurePasssword { get; set; }
    
        public virtual UserData UserData { get; set; }
    }
}
