//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectViolent
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersPhotos
    {
        public int PhotoID { get; set; }
        public int UserID { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual UserData UserData { get; set; }
    }
}
